### ISSUE TITLE
Chain problem

### ISSUE THREAD

**Issue by aidinzolghadr** [prime31/ZestKit#12]
Hi,

I'm trying to color tween to black and back with two tweens and chain. FullScreenImage is transparent before running the codes below. Here is my code:

```
    var chain = new TweenChain();

    chain.appendTween(FullScreenImage.ZKcolorTo( new Color(0, 0, 0, 1), 2f));
    chain.appendTween(FullScreenImage.ZKcolorTo( new Color(0, 0, 0, 0), 2f));
    chain.start();
```

problem is when it runs the first line and tweens to black, it suddenly resets and doesn't tween back to black with no alpha.

I think the effects of tweens are not permanent and after running first tween, the values somehow reset and that's why I can't see it tween back to transparent.

I'm trying to achieve the same effect I wanted with TransitionKit.

**Comment by aidinzolghadr** [comment]
Bump

**Comment by aidinzolghadr** [comment]
I suspect you can not call two ZKcolorTo calls right after another because I'm testing it with black to white and it fades to black nice and ok but then goes to state before the fade to black tween and then fades to white.

**Comment by prime31** [comment]
That tween should cycle to full black, then reset the original color and cycle that to transparent black. When you use any of the ZK\* methods the from value is captured immediately. I am assuming that you want to cycle to opaque black in the first tween and from opaque black to transparent black in the second. If that is correct then just set the from value of the second tween like so:

```
        var chain = new TweenChain();
        chain.appendTween( FullScreenImage.ZKcolorTo( new Color( 0, 0, 0, 1 ), 2f ) );
        chain.appendTween( FullScreenImage.ZKcolorTo( new Color( 0, 0, 0, 0 ), 2f ).setFrom( new Color( 0, 0, 0, 1 ) ) );
        chain.start();
```

**Comment by cubicme** [comment]
(aidinzolghadr here) Got it, I believe it should be mentioned that it works this way because other tween libraries don't. At least the ones I've worked with.

That being said, Is there anyway to make chains not to use values upfront and get values from the last chain?

Are other tween libraries by you, i.e. GoKit, like this?

**Comment by prime31** [comment]
As of now they always bind the from value when initialize is called

Mike

On Sep 19, 2015, at 11:20 AM, Ali Monemian notifications@github.com wrote:

(aidinzolghadr here) Got it, I believe it should be mentioned that it works this way because other tween libraries don't. At least the ones I've worked with.

That being said, Is there anyway to make chains not to use values upfront and get values from the last chain?

Are other tween libraries by you, i.e. GoKit, like this?

**Comment by r618** [comment]
Hi,
I understand the reasoning behind implementation, but I think it is bad design. The value for `setFrom` is known from previous tween and the function name `appendTween` implies that the next tween will continue where the previous one left off.
It took me a while now to set up completion handlers ( didn't realise there are setFrom calls and they make code more convoluted anyway ;)
I'll leave this here for consideration, if you don't mind.
