### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by sinbad** [prime31/ZestKit#26]
I've been taking a look at tween libraries and I really like the look of ZestKit, thanks for all your work on this and your previous libraries.

However, I don't believe the [license you picked](http://creativecommons.org/licenses/by-nc-sa/3.0/legalcode) actually supports your intended usage scenarios. The ReadMe says "You are free to use ZestKit in any and all games that you make", however the official license text prevents its use in any commercial games. I realise what you're trying to do is prevent the library's standalone resale, but that's not actually what the license says; legally anyone using it for commercial games is in breach of that license.

I've been publishing open source since 2001 and I totally understand where you're coming from; early on I released [things](http://ogre3d.org) under the LGPL with the intention of preventing exploitation, including exclusion clauses where necessary. Over the years however, including having to legally pursue a violation once which I *never* want to do again, I came to the conclusion that simpler licenses were better for everyone - I [wrote about this at length](http://www.stevestreeting.com/2009/09/15/my-evolving-view-of-open-source-licenses/) from my point of view as a publisher of open source if you're interested.

Of course this is your library and you can do whatever you want 😄 I just thought I'd let you know that as great as your library looks, I won't be able to use this library despite the ReadMe telling me I can, because the license is what matters at the end of the day. Maybe it will affect others too. That may or may not be a concern to you 😄 I applaud what you've done here either way.

Best of luck
Steve

**Comment by prime31** [comment]
The README addendum is actually a legally binding statement. The license has been checked out and given the thumbs up by several lawyers from some monster-sized game studios so all should be well on that front.

**Comment by Alan-FGR** [comment]
Sorry to comment on a closed issue, but I'm with @sinbad on this. I use DOTween but came across this library which seems quite good, however the license is a deal-breaker for me because even if 'lawyers from several studios' have given it a thumbs-up, my legal advising didn't and I'm extra cautious when it comes to licensing.

I echo what @sinbad said and I can't thank you enough for your contribution to the indie community @prime31, but from what I understand that license really doesn't fit the purpose and in general CC licenses are quite controversial, especially the definition of 'derivative works' and stuff like that. If it's not OK to use CC-SA arts in a proprietary game, I don't see how it's OK to use this.

Another point is that 'monster-sized studios' have the money to go through lengthy court cases while indies generally don't and won't risk it, besides that a thumbs-up from a lawyer doesn't mean a thumbs-up from the court and I haven't found a single IP law attorneys who won't tell you to stay away from CC like the plague.

I agree with @sinbad that the simpler the better, and CC licenses aren't exactly simple, but most importantly they aren't clear, in the end it's all up to interpretation and subjectivity isn't something you want in a court litigation.

I'd like to ask those lawyers who gave this license a thumbs-up if they think it'd be OK to use, say, the Castle Crashers soundtrack in a commercial game, or to make a Cards Against Humanity video game, because I honestly don't see the difference but I'm pretty sure that isn't OK.

Again, sorry to bring this to your attention once more, but I believe by using a license like that you're greatly limiting the potential users of this library because the most popular interpretation of that license is the one @sinbad mentioned: "legally anyone using it for commercial games is in breach of that license."

**Comment by prime31** [comment]
If it makes your legal counsel happy feel free to send over a document specifically naming any games you want to use ZestKit in and I'd be more than happy to sign off on them.

**Comment by Alan-FGR** [comment]
@prime31 that's very kind, thank you sir! I think one thing you could do to clarify a bit the purpose of the license is to explicitly state that anyone is free to use the code in a proprietary, closed-source commercial game as long as they don't sell ZestKit or products that include it in the source form.

The problem with the addendum is that it doesn't actually reject any of the implications of the license, one could interpret it as: "You are free to use ZestKit in any and all games that you make. [... as long as you abide to the other terms of the CC-NC-SA license]".

Again, sorry to bring this tedious subject to your attention and also to @sinbad (if you're getting notified), but it's not OK to use CC-BY-NC-SA contents in a closed-source, commercial game according to my understanding of that license.
