### ISSUE TITLE
TweenParty .setCompletionHandler error

### ISSUE THREAD

**Issue by AniMittra** [prime31/ZestKit#7]
I'm trying to set a callback for my tween party the same way I have for tween chains and other standalone tweens like ZKpositionTo but I am getting this error. I think it is because TweenParty is built off of the FloatTween class but I am not sure. This is my first experience using Actions and lambdas so I am not sure what I need to cast.

Cannot implicitly convert type 'Prime31.ZestKit.ITween<float>' to 'Prime31.ZestKit.TweenParty'. An explicit conversion exists (are you missing a cast?) 

here's my code:

``` C#
            // create animation party for collapse
            TweenParty collapseParty = new TweenParty(Constants.Anim_GemToDuration)
                .setCompletionHandler( tw =>
                    {
                        AnimationCompleteHandler("Collapse Animation");
                    });

```

**Comment by prime31** [comment]
TweenPartys are indeed built off of floats which is all that they require internally. 

Mike

On Jun 22, 2015, at 2:43 AM, AniMittra notifications@github.com wrote:

I'm trying to set a callback for my tween party the same way I have for tween chains and other standalone tweens like ZKpositionTo but I am getting this error. I think it is because TweenParty is built off of the FloatTween class but I am not sure. This is my first experience using Actions and lambdas so I am not sure what I need to cast.

Cannot implicitly convert type 'Prime31.ZestKit.ITween' to 'Prime31.ZestKit.TweenParty'. An explicit conversion exists (are you missing a cast?)

here's my code:

```
        // create animation party for collapse
        TweenParty collapseParty = new TweenParty(Constants.Anim_GemToDuration)
            .setCompletionHandler( tw =>
                {
                    AnimationCompleteHandler("Collapse Animation");
                });
```
